### PR TITLE
Make generate.py compatible with Python 3

### PR DESCRIPTION
**Pull request by abitrolly**
I used docker image to produce the patch using new template.

    ./02cowrite.sh -templates /opt/catalogue/Python2 -d /opt -f generate.py -in-place

The content of `02cowrite.sh`.

    #!/bin/bash

    podman run --rm -i -a stdin -a stdout -a stderr -v "$(pwd)":/opt:Z comby/comby "$@"

### CODE REVIEW

**Comment by abitrolly** [comment]
@rvantonder should this repository run `generate.py` as a part of testing?

**Comment by rvantonder** [comment]
>  should this repository run generate.py as a part of testing?

That would be a nice to have! I'll create an issue to track this (my hands are a bit full to do this immediately)

**Comment by rvantonder** [comment]
Also: sorry for the delay on these. I was ill and in bed all last week :(

**Comment by abitrolly** [comment]
Absolutely no problems with that

> That would be a nice to have! I'll create an issue to track this (my hands are a bit full to do this immediately)

Just turn this repo on in https://travis-ci.com/comby-tools/ and #4 should work.

**Pull request merged**
